"use client";

import { useRef, useCallback, useState } from "react";
import { motion } from "motion/react";
import type { ShareCardData } from "@/types/league";

// ─── Card visual component ─────────────────────────────────────────

function ShareCardVisual({
  data,
  cardRef,
}: {
  data: ShareCardData;
  cardRef: React.RefObject<HTMLDivElement | null>;
}) {
  const record = `${data.wins}-${data.losses}${
    data.ties > 0 ? `-${data.ties}` : ""
  }`;

  return (
    <div
      ref={cardRef}
      id="share-card-canvas"
      className="relative w-full max-w-md overflow-hidden rounded-2xl"
      style={{
        background:
          "linear-gradient(135deg, #0a0a12 0%, #12121e 40%, #1a1028 70%, #0a0a12 100%)",
      }}
    >
      {/* Decorative elements */}
      <div className="absolute inset-0 pointer-events-none">
        {/* Gold accent corner */}
        <div
          className="absolute -right-10 -top-10 h-40 w-40 rounded-full opacity-20"
          style={{
            background:
              "radial-gradient(circle, rgba(245,197,24,0.4) 0%, transparent 70%)",
          }}
        />
        {/* Purple accent */}
        <div
          className="absolute -bottom-10 -left-10 h-32 w-32 rounded-full opacity-15"
          style={{
            background:
              "radial-gradient(circle, rgba(168,85,247,0.4) 0%, transparent 70%)",
          }}
        />
        {/* Grid pattern */}
        <div
          className="absolute inset-0 opacity-[0.03]"
          style={{
            backgroundImage:
              "radial-gradient(rgba(255,255,255,0.5) 1px, transparent 1px)",
            backgroundSize: "24px 24px",
          }}
        />
      </div>

      {/* Content */}
      <div className="relative z-10 p-6 sm:p-8">
        {/* Header */}
        <div className="mb-6 flex items-center justify-between">
          <div>
            <h2 className="bg-gradient-to-r from-amber-300 via-yellow-200 to-amber-400 bg-clip-text text-2xl font-black tracking-tight text-transparent">
              14-0
            </h2>
            <p className="text-[10px] uppercase tracking-widest text-zinc-500">
              IPL Draft Simulator
            </p>
          </div>
          {data.isPerfect && (
            <div className="flex items-center gap-1.5 rounded-full border border-amber-500/40 bg-amber-500/10 px-3 py-1">
              <span className="text-sm">🏆</span>
              <span className="text-[10px] font-bold uppercase tracking-wider text-amber-400">
                PERFECT
              </span>
            </div>
          )}
        </div>

        {/* Team name */}
        <div className="mb-6">
          <span className="text-[10px] uppercase tracking-wider text-zinc-500">
            Team
          </span>
          <h3 className="mt-1 text-lg font-bold text-white">
            {data.teamName}
          </h3>
        </div>

        {/* Record */}
        <div className="mb-6 flex items-baseline gap-2">
          <span
            className={`text-4xl font-black tabular-nums ${
              data.isPerfect
                ? "bg-gradient-to-r from-amber-300 to-yellow-300 bg-clip-text text-transparent"
                : data.wins > data.losses
                ? "text-emerald-400"
                : "text-red-400"
            }`}
          >
            {record}
          </span>
          <span className="text-sm text-zinc-500">record</span>
        </div>

        {/* Stats grid */}
        <div className="grid grid-cols-3 gap-3 rounded-xl border border-white/8 bg-white/[0.03] p-3">
          <div className="text-center">
            <span className="block text-lg font-black text-blue-400 tabular-nums">
              {data.totalRuns}
            </span>
            <span className="text-[9px] uppercase tracking-wider text-zinc-500">
              Runs
            </span>
          </div>
          <div className="text-center">
            <span className="block text-lg font-black text-purple-400 tabular-nums">
              {data.totalWickets}
            </span>
            <span className="text-[9px] uppercase tracking-wider text-zinc-500">
              Wickets
            </span>
          </div>
          <div className="text-center">
            <span className="block text-lg font-black text-accent-gold tabular-nums">
              {data.bestScore}
            </span>
            <span className="text-[9px] uppercase tracking-wider text-zinc-500">
              Best Score
            </span>
          </div>
        </div>

        {/* Footer */}
        <div className="mt-6 flex items-center justify-between border-t border-white/5 pt-4">
          <span className="text-[10px] text-zinc-600">
            Generated by 14-0 Draft Simulator
          </span>
          <span className="text-[10px] font-semibold text-zinc-500">
            {new Date().toLocaleDateString("en-IN", {
              day: "numeric",
              month: "short",
              year: "numeric",
            })}
          </span>
        </div>
      </div>
    </div>
  );
}

// ─── ShareCard Component ────────────────────────────────────────────

interface ShareCardProps {
  data: ShareCardData;
}

export default function ShareCard({ data }: ShareCardProps) {
  const cardRef = useRef<HTMLDivElement>(null);
  const [copyFeedback, setCopyFeedback] = useState<string | null>(null);

  // Generate shareable text
  const shareText = useCallback(() => {
    const record = `${data.wins}-${data.losses}${
      data.ties > 0 ? `-${data.ties}` : ""
    }`;
    const emoji = data.isPerfect ? "🏆" : data.wins > data.losses ? "✅" : "🏏";
    return `${emoji} My IPL Draft Season: ${record}\n\n` +
      `Team: ${data.teamName}\n` +
      `📊 ${data.totalRuns} runs | ${data.totalWickets} wickets | Best: ${data.bestScore}\n` +
      (data.isPerfect ? "\n🔥 PERFECT 14-0 SEASON! 🔥\n" : "") +
      `\n#14dash0 #IPLDraftSimulator`;
  }, [data]);

  // Copy to clipboard
  const handleCopyText = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(shareText());
      setCopyFeedback("Copied!");
      setTimeout(() => setCopyFeedback(null), 2000);
    } catch {
      setCopyFeedback("Failed to copy");
      setTimeout(() => setCopyFeedback(null), 2000);
    }
  }, [shareText]);

  // Native share API
  const handleShare = useCallback(async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: "My IPL Draft Season — 14-0",
          text: shareText(),
        });
      } catch {
        // User cancelled share
      }
    } else {
      handleCopyText();
    }
  }, [shareText, handleCopyText]);

  // Download as image (using html2canvas-like approach with canvas)
  const handleDownload = useCallback(async () => {
    if (!cardRef.current) return;

    try {
      // Use the canvas approach for image generation
      const el = cardRef.current;
      const canvas = document.createElement("canvas");
      const scale = 2; // Retina
      canvas.width = el.offsetWidth * scale;
      canvas.height = el.offsetHeight * scale;
      const ctx = canvas.getContext("2d");
      if (!ctx) return;

      // Draw background
      const gradient = ctx.createLinearGradient(0, 0, canvas.width, canvas.height);
      gradient.addColorStop(0, "#0a0a12");
      gradient.addColorStop(0.4, "#12121e");
      gradient.addColorStop(0.7, "#1a1028");
      gradient.addColorStop(1, "#0a0a12");
      ctx.fillStyle = gradient;
      ctx.fillRect(0, 0, canvas.width, canvas.height);

      // Title
      ctx.fillStyle = "#f5c518";
      ctx.font = `bold ${32 * scale}px system-ui, -apple-system, sans-serif`;
      ctx.fillText("14-0", 40 * scale, 50 * scale);

      ctx.fillStyle = "#6b7280";
      ctx.font = `${10 * scale}px system-ui`;
      ctx.fillText("IPL DRAFT SIMULATOR", 40 * scale, 66 * scale);

      // Team
      ctx.fillStyle = "#6b7280";
      ctx.font = `${10 * scale}px system-ui`;
      ctx.fillText("TEAM", 40 * scale, 100 * scale);

      ctx.fillStyle = "#f0f0f5";
      ctx.font = `bold ${18 * scale}px system-ui`;
      ctx.fillText(data.teamName, 40 * scale, 120 * scale);

      // Record
      const record = `${data.wins}-${data.losses}${data.ties > 0 ? `-${data.ties}` : ""}`;
      ctx.fillStyle = data.isPerfect
        ? "#f5c518"
        : data.wins > data.losses
        ? "#22c55e"
        : "#ef4444";
      ctx.font = `900 ${40 * scale}px system-ui`;
      ctx.fillText(record, 40 * scale, 170 * scale);

      ctx.fillStyle = "#6b7280";
      ctx.font = `${14 * scale}px system-ui`;
      ctx.fillText("record", 40 * scale + ctx.measureText(record).width + 10 * scale, 170 * scale);

      // Stats
      const statsY = 210 * scale;
      const statsItems = [
        { label: "RUNS", value: String(data.totalRuns), color: "#3b82f6" },
        { label: "WKTS", value: String(data.totalWickets), color: "#a855f7" },
        { label: "BEST", value: data.bestScore, color: "#f5c518" },
      ];

      const statWidth = (canvas.width - 80 * scale) / 3;
      statsItems.forEach((item, i) => {
        const x = 40 * scale + i * statWidth;
        ctx.fillStyle = item.color;
        ctx.font = `900 ${22 * scale}px system-ui`;
        ctx.fillText(item.value, x, statsY);

        ctx.fillStyle = "#6b7280";
        ctx.font = `${9 * scale}px system-ui`;
        ctx.fillText(item.label, x, statsY + 16 * scale);
      });

      // Perfect badge
      if (data.isPerfect) {
        ctx.fillStyle = "#f5c518";
        ctx.font = `bold ${14 * scale}px system-ui`;
        ctx.fillText("🏆 PERFECT SEASON", 40 * scale, statsY + 50 * scale);
      }

      // Download
      const link = document.createElement("a");
      link.download = `14-0-season-${Date.now()}.png`;
      link.href = canvas.toDataURL("image/png");
      link.click();

      setCopyFeedback("Downloaded!");
      setTimeout(() => setCopyFeedback(null), 2000);
    } catch {
      setCopyFeedback("Download failed");
      setTimeout(() => setCopyFeedback(null), 2000);
    }
  }, [data]);

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className="space-y-4"
    >
      <h3 className="text-sm font-bold text-white">Share Your Season</h3>

      {/* Card preview */}
      <ShareCardVisual data={data} cardRef={cardRef} />

      {/* Action buttons */}
      <div className="flex flex-wrap gap-2">
        <motion.button
          whileHover={{ scale: 1.03 }}
          whileTap={{ scale: 0.97 }}
          onClick={handleShare}
          className="flex items-center gap-2 rounded-xl bg-gradient-to-r from-accent-gold/20 to-amber-500/20 border border-accent-gold/30 px-4 py-2.5 text-sm font-bold text-accent-gold transition-all hover:from-accent-gold/30 hover:to-amber-500/30"
        >
          📤 Share
        </motion.button>

        <motion.button
          whileHover={{ scale: 1.03 }}
          whileTap={{ scale: 0.97 }}
          onClick={handleCopyText}
          className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/[0.03] px-4 py-2.5 text-sm font-medium text-zinc-300 transition-all hover:bg-white/[0.06]"
        >
          📋 Copy Text
        </motion.button>

        <motion.button
          whileHover={{ scale: 1.03 }}
          whileTap={{ scale: 0.97 }}
          onClick={handleDownload}
          className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/[0.03] px-4 py-2.5 text-sm font-medium text-zinc-300 transition-all hover:bg-white/[0.06]"
        >
          📥 Download Image
        </motion.button>
      </div>

      {/* Feedback toast */}
      {copyFeedback && (
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: 10 }}
          className="inline-flex items-center gap-1.5 rounded-lg border border-emerald-500/30 bg-emerald-500/10 px-3 py-1.5 text-xs font-semibold text-emerald-400"
        >
          ✓ {copyFeedback}
        </motion.div>
      )}
    </motion.div>
  );
}
