"""add prime_rating and season_rating

Revision ID: 2daa240f7f8b
Revises: 666d596c1f37
Create Date: 2026-06-12 00:31:17.552580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2daa240f7f8b'
down_revision: Union[str, Sequence[str], None] = '666d596c1f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_seasons', sa.Column('prime_rating', sa.Integer(), server_default='50', nullable=False))
    op.add_column('player_seasons', sa.Column('season_rating', sa.Integer(), server_default='50', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_seasons', 'season_rating')
    op.drop_column('player_seasons', 'prime_rating')
    # ### end Alembic commands ###
