"""add player_season_id to draft_picks

Revision ID: 4b825b3f4516
Revises: 9fcd2f7f1839
Create Date: 2026-06-11 12:58:56.338319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b825b3f4516'
down_revision: Union[str, Sequence[str], None] = '9fcd2f7f1839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft_picks', sa.Column('player_season_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_draft_picks_player_season_id'), 'draft_picks', ['player_season_id'], unique=False)
    op.create_foreign_key(None, 'draft_picks', 'player_seasons', ['player_season_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'draft_picks', type_='foreignkey')
    op.drop_index(op.f('ix_draft_picks_player_season_id'), table_name='draft_picks')
    op.drop_column('draft_picks', 'player_season_id')
    # ### end Alembic commands ###
