"""Add Match model and update MatchEvent

Revision ID: 61b3920ffd81
Revises: 4b825b3f4516
Create Date: 2026-06-11 13:16:22.699939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61b3920ffd81'
down_revision: Union[str, Sequence[str], None] = '4b825b3f4516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('draft_session_id', sa.Uuid(), nullable=False),
    sa.Column('match_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('user_score', sa.Integer(), nullable=False),
    sa.Column('user_wickets', sa.Integer(), nullable=False),
    sa.Column('opponent_score', sa.Integer(), nullable=False),
    sa.Column('opponent_wickets', sa.Integer(), nullable=False),
    sa.Column('winner', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['draft_session_id'], ['draft_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_draft_session_id'), 'matches', ['draft_session_id'], unique=False)
    op.create_table('match_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('ball_number', sa.Integer(), nullable=False),
    sa.Column('over_number', sa.Integer(), nullable=False),
    sa.Column('batter_id', sa.Uuid(), nullable=False),
    sa.Column('bowler_id', sa.Uuid(), nullable=False),
    sa.Column('runs_scored', sa.Integer(), nullable=False),
    sa.Column('extras', sa.Integer(), nullable=False),
    sa.Column('wicket_type', sa.String(length=50), nullable=True),
    sa.Column('event_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['batter_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bowler_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_events_batter_id'), 'match_events', ['batter_id'], unique=False)
    op.create_index(op.f('ix_match_events_bowler_id'), 'match_events', ['bowler_id'], unique=False)
    op.create_index(op.f('ix_match_events_match_id'), 'match_events', ['match_id'], unique=False)
    op.drop_index(op.f('ix_match_logs_batter_id'), table_name='match_logs')
    op.drop_index(op.f('ix_match_logs_bowler_id'), table_name='match_logs')
    op.drop_index(op.f('ix_match_logs_match_id'), table_name='match_logs')
    op.drop_table('match_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('match_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ball_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('over_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('batter_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('bowler_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('runs_scored', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('extras', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('wicket_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('event_meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['batter_id'], ['players.id'], name=op.f('match_logs_batter_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bowler_id'], ['players.id'], name=op.f('match_logs_bowler_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('match_logs_pkey'))
    )
    op.create_index(op.f('ix_match_logs_match_id'), 'match_logs', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_logs_bowler_id'), 'match_logs', ['bowler_id'], unique=False)
    op.create_index(op.f('ix_match_logs_batter_id'), 'match_logs', ['batter_id'], unique=False)
    op.drop_index(op.f('ix_match_events_match_id'), table_name='match_events')
    op.drop_index(op.f('ix_match_events_bowler_id'), table_name='match_events')
    op.drop_index(op.f('ix_match_events_batter_id'), table_name='match_events')
    op.drop_table('match_events')
    op.drop_index(op.f('ix_matches_draft_session_id'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
