"""add_team_name_and_overs_to_match

Revision ID: 666d596c1f37
Revises: 61b3920ffd81
Create Date: 2026-06-11 15:10:12.569008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '666d596c1f37'
down_revision: Union[str, Sequence[str], None] = '61b3920ffd81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('opponent_team', sa.String(length=100), nullable=True))
    op.add_column('matches', sa.Column('user_team', sa.String(length=100), nullable=False))
    op.add_column('matches', sa.Column('user_overs', sa.Float(), nullable=False))
    op.add_column('matches', sa.Column('opponent_overs', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'opponent_overs')
    op.drop_column('matches', 'user_overs')
    op.drop_column('matches', 'user_team')
    op.drop_column('matches', 'opponent_team')
    # ### end Alembic commands ###
