"""Initial schema migration

Revision ID: 9fcd2f7f1839
Revises: 
Create Date: 2026-06-11 03:12:05.230142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9fcd2f7f1839'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('budget_remaining', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_sessions_user_id'), 'draft_sessions', ['user_id'], unique=False)
    op.create_table('franchises',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_franchises_code'), 'franchises', ['code'], unique=True)
    op.create_table('players',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_overseas', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=False)
    op.create_table('seasons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seasons_year'), 'seasons', ['year'], unique=True)
    op.create_table('draft_picks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('draft_session_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('pick_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['draft_session_id'], ['draft_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_picks_draft_session_id'), 'draft_picks', ['draft_session_id'], unique=False)
    op.create_index(op.f('ix_draft_picks_player_id'), 'draft_picks', ['player_id'], unique=False)
    op.create_table('franchise_seasons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('franchise_id', sa.Uuid(), nullable=False),
    sa.Column('season_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('franchise_id', 'season_id', name='uq_franchise_season')
    )
    op.create_index(op.f('ix_franchise_seasons_franchise_id'), 'franchise_seasons', ['franchise_id'], unique=False)
    op.create_index(op.f('ix_franchise_seasons_season_id'), 'franchise_seasons', ['season_id'], unique=False)
    op.create_table('match_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('ball_number', sa.Integer(), nullable=False),
    sa.Column('over_number', sa.Integer(), nullable=False),
    sa.Column('batter_id', sa.Uuid(), nullable=False),
    sa.Column('bowler_id', sa.Uuid(), nullable=False),
    sa.Column('runs_scored', sa.Integer(), nullable=False),
    sa.Column('extras', sa.Integer(), nullable=False),
    sa.Column('wicket_type', sa.String(length=50), nullable=True),
    sa.Column('event_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['batter_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bowler_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_logs_batter_id'), 'match_logs', ['batter_id'], unique=False)
    op.create_index(op.f('ix_match_logs_bowler_id'), 'match_logs', ['bowler_id'], unique=False)
    op.create_index(op.f('ix_match_logs_match_id'), 'match_logs', ['match_id'], unique=False)
    op.create_table('player_seasons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('season_id', sa.Uuid(), nullable=False),
    sa.Column('franchise_id', sa.Uuid(), nullable=False),
    sa.Column('balls_faced', sa.Integer(), nullable=False),
    sa.Column('runs_scored', sa.Integer(), nullable=False),
    sa.Column('balls_bowled', sa.Integer(), nullable=False),
    sa.Column('wickets_taken', sa.Integer(), nullable=False),
    sa.Column('raw_batting_rating', sa.Float(), nullable=False),
    sa.Column('raw_bowling_rating', sa.Float(), nullable=False),
    sa.Column('percentile_batting', sa.Integer(), nullable=False),
    sa.Column('percentile_bowling', sa.Integer(), nullable=False),
    sa.Column('credit_cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season_id', 'franchise_id', name='uq_player_season_franchise')
    )
    op.create_index(op.f('ix_player_seasons_franchise_id'), 'player_seasons', ['franchise_id'], unique=False)
    op.create_index(op.f('ix_player_seasons_player_id'), 'player_seasons', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_seasons_season_id'), 'player_seasons', ['season_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_seasons_season_id'), table_name='player_seasons')
    op.drop_index(op.f('ix_player_seasons_player_id'), table_name='player_seasons')
    op.drop_index(op.f('ix_player_seasons_franchise_id'), table_name='player_seasons')
    op.drop_table('player_seasons')
    op.drop_index(op.f('ix_match_logs_match_id'), table_name='match_logs')
    op.drop_index(op.f('ix_match_logs_bowler_id'), table_name='match_logs')
    op.drop_index(op.f('ix_match_logs_batter_id'), table_name='match_logs')
    op.drop_table('match_logs')
    op.drop_index(op.f('ix_franchise_seasons_season_id'), table_name='franchise_seasons')
    op.drop_index(op.f('ix_franchise_seasons_franchise_id'), table_name='franchise_seasons')
    op.drop_table('franchise_seasons')
    op.drop_index(op.f('ix_draft_picks_player_id'), table_name='draft_picks')
    op.drop_index(op.f('ix_draft_picks_draft_session_id'), table_name='draft_picks')
    op.drop_table('draft_picks')
    op.drop_index(op.f('ix_seasons_year'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_franchises_code'), table_name='franchises')
    op.drop_table('franchises')
    op.drop_index(op.f('ix_draft_sessions_user_id'), table_name='draft_sessions')
    op.drop_table('draft_sessions')
    # ### end Alembic commands ###
